### ISSUE TITLE
Backslash paths on Windows are not escaped

### ISSUE THREAD

**Issue by Meshiest** [vleue/bevy_embedded_assets#1]
### Issue

Paths on Windows that use backslashes are not properly escaped and result in invalid codegen.

### Replication

1. Be on Windows in a bevy project folder
2. Create a `.cargo/config.toml` in project folder with (expects `assets` to also be in project root)
    ```toml
    [env]
    BEVY_ASSET_PATH = { relative = true, value = "assets" }
    ```
3. Observe invalid output `target/debug/build/bevy_embedded_assets_HASH/out/include_all_assets.rs`
    ```rust
    /// Generated function that will add all assets to the [`EmbeddedAssetIo`].
    #[allow(unused_variables)] pub fn include_all_assets(embedded: &mut EmbeddedAssetIo){
    embedded.add_asset(std::path::Path::new("face.blend"), include_bytes!("path\prefix\assets\myAsset.ext"));
    ```

### Expected outcome

Paths with backslashes should have the backslashes escaped.

Example expected output:

```rust
/// Generated function that will add all assets to the [`EmbeddedAssetIo`].
#[allow(unused_variables)] pub fn include_all_assets(embedded: &mut EmbeddedAssetIo){
embedded.add_asset(std::path::Path::new("face.blend"), include_bytes!("path\\prefix\\assets\\myAsset.ext"));
```

**Comment by mockersf** [comment]
thanks, should be fixed on Bevy 0.5 and on main 👍
